language: java
jdk:
  - oraclejdk8
before_script:
  - pip install --user codecov
after_success:
  - codecov
  - mvn deploy -DskipTests=true -POJO --settings ./.travis/maven-settings.xml
  - mvn deploy -DskipTests=true -PSONATYPE --settings ./.travis/maven-settings.xml
